// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    directUrl: process.env.DIRECT_URL,
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});

// import "dotenv/config";
// import { defineConfig } from "@prisma/config"; // '@' இருப்பதை உறுதி செய்யவும்

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   datasource: {

//     url: process.env.DIRECT_URL, 
//   },
// });